### ISSUE TITLE
asciify-image can’t be installed on current node/npm on OSX 10.12.1 …

### ISSUE THREAD

**Issue by fooness** [ajay-gandhi/asciify-image#3]
Hello there, unfortunately, asciify-image can’t be installed on current node/npm on OSX 10.12.1 … some problem with lwip and/or lodash. Could you maybe look into this? Thank you very much.

```
npm install asciify-image

lwip@0.0.8 install node_modules/asciify-image/node_modules/lwip
node-gyp rebuild

 CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../nan/nan.h:182:
../../nan/nan_maybe_43_inl.h:221:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
 return array->CloneElementAt(GetCurrentContext(), index);
               ^
/Users/and1/.node-gyp/7.0.0/include/node/v8.h:3056:36: note: 'CloneElementAt' has been explicitly marked deprecated here
               MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                  ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
In file included from ../../nan/nan.h:188:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
 return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                           ^
/Users/and1/.node-gyp/7.0.0/include/node/v8.h:4048:56: note: 'New' has been explicitly marked deprecated here
 V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                      ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
     v8::Isolate::GCEpilogueCallback callback
     ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
     v8::Isolate::GCEpilogueCallback callback) {
     ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
     v8::Isolate::GCPrologueCallback callback
     ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
     v8::Isolate::GCPrologueCallback callback) {
     ~~~~~~~~~~~~~^
../../nan/nan.h:1927:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
 return obj->SetAccessor(
             ^
/Users/and1/.node-gyp/7.0.0/include/node/v8.h:2761:22: note: 'SetAccessor' has been explicitly marked deprecated here
               bool SetAccessor(Local<Name> name,
                    ^
3 warnings and 4 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd node_modules/asciify-image/node_modules/lwip
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
./
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open ‘./package.json'
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "asciify-image"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log
npm ERR! code 1
```

**Comment by ajay-gandhi** [comment]
Fixed in 649d260.

**Comment by fooness** [comment]
Thank you!

Still getting some warnings, though. Some looking more serious to me, like:

```
npm install asciify-image
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp:8:56: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    _height(0), _channels(0), _trans(false), _metadata("") {
```

**Comment by ajay-gandhi** [comment]
The deprecation warning is from a dependency of asciify-image, i.e. not something I can control directly. If I get some time, I'll try to put a pull request through to that package to resolve this issue. The remaining warnings are when compiling that same package, and these can be ignored as long as compilation is successful.

**Comment by fooness** [comment]
Thank you very much!
